version: '3'

networks:
  web_net:
    external: true

services:
  vueui:
    container_name: hex-lowcode-engine-starter
    image: yuanjunjie/hex-lowcode-engine-starter:dev
    restart: always
    networks:
      - web_net
    ports:
      - '8080:80'
