version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: stage-b5681ffe
    displayName: hex-lowcode-engine-starter
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: 7f8eeca0-e741-013b-c978-2a53ec0b7704
        tag: hex-lowcode-engine-starter
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: 7f8eeca0-e741-013b-c978-2a53ec0b7704
        image: hex-lowcode-engine-starter
        command:
          - '# 请在此输入您想执行的脚本'
          - echo 'Hello Gitee!'
          - ls
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_docker
