name: CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 14.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build docker
        run: |
          docker build -t yuanjunjie/hex-lowcode-engine-starter:dev .

      - name: Login to Docker Registry
        run: | 
          sudo su
          docker login --username=${{ secrets.DOCKER_USER_NAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Registry
        run: |
          sudo su
          sudo docker push yuanjunjie/hex-lowcode-engine-starter:dev

  deploy:
    needs: [build]
    name: Deploy
    runs-on: fd-dev

    steps:
      - uses: actions/checkout@v2

      - name: Update docker images
        run: |
          sudo su
          sudo docker pull yuanjunjie/hex-lowcode-engine-starter:dev

      - name: Login to Docker Registry 
        run: |
          sudo su
          sudo docker login --username=${{ secrets.DOCKER_USER_NAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Run
        run: |
          sudo su
          ls 
          sudo docker compose -f docker-compose.yml up -d
